/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/layout'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAlgoritmosAlgortimosBasicosRouteImport } from './routes/(public)/algoritmos/algortimos-basicos'
import { Route as publicAlgoritmosAlgoritmosGeneticosRouteImport } from './routes/(public)/algoritmos/algoritmos-geneticos'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicAlgoritmosAlgortimosBasicosRoute =
  publicAlgoritmosAlgortimosBasicosRouteImport.update({
    id: '/algoritmos/algortimos-basicos',
    path: '/algoritmos/algortimos-basicos',
    getParentRoute: () => publicLayoutRoute,
  } as any)
const publicAlgoritmosAlgoritmosGeneticosRoute =
  publicAlgoritmosAlgoritmosGeneticosRouteImport.update({
    id: '/algoritmos/algoritmos-geneticos',
    path: '/algoritmos/algoritmos-geneticos',
    getParentRoute: () => publicLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/algoritmos/algoritmos-geneticos': typeof publicAlgoritmosAlgoritmosGeneticosRoute
  '/algoritmos/algortimos-basicos': typeof publicAlgoritmosAlgortimosBasicosRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/algoritmos/algoritmos-geneticos': typeof publicAlgoritmosAlgoritmosGeneticosRoute
  '/algoritmos/algortimos-basicos': typeof publicAlgoritmosAlgortimosBasicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(public)/algoritmos/algoritmos-geneticos': typeof publicAlgoritmosAlgoritmosGeneticosRoute
  '/(public)/algoritmos/algortimos-basicos': typeof publicAlgoritmosAlgortimosBasicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algoritmos/algoritmos-geneticos'
    | '/algoritmos/algortimos-basicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algoritmos/algoritmos-geneticos'
    | '/algoritmos/algortimos-basicos'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/'
    | '/(public)/algoritmos/algoritmos-geneticos'
    | '/(public)/algoritmos/algortimos-basicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/algoritmos/algortimos-basicos': {
      id: '/(public)/algoritmos/algortimos-basicos'
      path: '/algoritmos/algortimos-basicos'
      fullPath: '/algoritmos/algortimos-basicos'
      preLoaderRoute: typeof publicAlgoritmosAlgortimosBasicosRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/algoritmos/algoritmos-geneticos': {
      id: '/(public)/algoritmos/algoritmos-geneticos'
      path: '/algoritmos/algoritmos-geneticos'
      fullPath: '/algoritmos/algoritmos-geneticos'
      preLoaderRoute: typeof publicAlgoritmosAlgoritmosGeneticosRouteImport
      parentRoute: typeof publicLayoutRoute
    }
  }
}

interface publicLayoutRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAlgoritmosAlgoritmosGeneticosRoute: typeof publicAlgoritmosAlgoritmosGeneticosRoute
  publicAlgoritmosAlgortimosBasicosRoute: typeof publicAlgoritmosAlgortimosBasicosRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAlgoritmosAlgoritmosGeneticosRoute:
    publicAlgoritmosAlgoritmosGeneticosRoute,
  publicAlgoritmosAlgortimosBasicosRoute:
    publicAlgoritmosAlgortimosBasicosRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
